name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint@10.10.0 eslint-plugin-react-hooks@7.1.1 eslint-plugin-react-refresh@0.5.6
      - name: ESLint Report
        run: npx eslint .
  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@17.15.0 stylelint-config-standard-css@40.0.0
      - name: Stylelint Report
        run: npx stylelint "**/*.css"
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi